// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class Employee
    {
        public Employee()
        {
            Orders = new HashSet<Order>();
            WarehouseTransactions = new HashSet<WarehouseTransaction>();
        }

        public int EmployeeId { get; set; }
        public string FullName { get; set; }
        public DateTime? BirthDate { get; set; }
        public string PassportData { get; set; }
        public string BankDetails { get; set; }
        public string MaritalStatus { get; set; }
        public string HealthStatus { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public bool? AccountStatus { get; set; }
        public DateTime? LastLogin { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<WarehouseTransaction> WarehouseTransactions { get; set; }
    }
}