// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class Material
    {
        public Material()
        {
            ProductMaterials = new HashSet<ProductMaterial>();
            WarehouseTransactions = new HashSet<WarehouseTransaction>();
        }

        public int MaterialId { get; set; }
        public string MaterialType { get; set; }
        public string Name { get; set; }
        public int SupplierId { get; set; }
        public int PackageQuantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal Cost { get; set; }
        public decimal CurrentStock { get; set; }
        public decimal MinStockLevel { get; set; }

        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterials { get; set; }
        public virtual ICollection<WarehouseTransaction> WarehouseTransactions { get; set; }
    }
}