// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int OrderId { get; set; }
        public int PartnerId { get; set; }
        public int ManagerId { get; set; }
        public DateTime? OrderDate { get; set; }
        public decimal? PrepaymentAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal? DiscountAmount { get; set; }
        public string Status { get; set; }
        public string DeliveryMethod { get; set; }

        public virtual Employee Manager { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}