// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class PartnerType
    {
        public PartnerType()
        {
            Partners = new HashSet<Partner>();
        }

        public int PartnerTypeId { get; set; }
        public string TypeName { get; set; }

        public virtual ICollection<Partner> Partners { get; set; }
    }
}