// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class PartnerSalesHistory
    {
        public int HistoryId { get; set; }
        public int PartnerId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal SaleAmount { get; set; }

        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}