// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class Partner
    {
        public Partner()
        {
            Orders = new HashSet<Order>();
            PartnerSalesHistories = new HashSet<PartnerSalesHistory>();
            SalesPoints = new HashSet<SalesPoint>();
        }

        public int PartnerId { get; set; }
        public int PartnerTypeId { get; set; }
        public string CompanyName { get; set; }
        public string TaxId { get; set; }
        public string LegalAddress { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public decimal? Rating { get; set; }
        public decimal? TotalSalesVolume { get; set; }
        public decimal? CurrentDiscount { get; set; }

        public virtual PartnerType PartnerType { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PartnerSalesHistory> PartnerSalesHistories { get; set; }
        public virtual ICollection<SalesPoint> SalesPoints { get; set; }
    }
}