// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class Product
    {
        public Product()
        {
            OrderItems = new HashSet<OrderItem>();
            PartnerSalesHistories = new HashSet<PartnerSalesHistory>();
            ProductMaterials = new HashSet<ProductMaterial>();
            WarehouseTransactions = new HashSet<WarehouseTransaction>();
        }

        public int ProductId { get; set; }
        public int ProductTypeId { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        public decimal MinPartnerPrice { get; set; }
        public decimal PackageLength { get; set; }
        public decimal PackageWidth { get; set; }
        public decimal PackageHeight { get; set; }
        public int ProductionTime { get; set; }
        public decimal ProductionCost { get; set; }
        public int WorkshopNumber { get; set; }
        public int RequiredWorkers { get; set; }

        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<PartnerSalesHistory> PartnerSalesHistories { get; set; }
        public virtual ICollection<ProductMaterial> ProductMaterials { get; set; }
        public virtual ICollection<WarehouseTransaction> WarehouseTransactions { get; set; }
    }
}