// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class SalesPoint
    {
        public int SalesPointId { get; set; }
        public int PartnerId { get; set; }
        public string PointType { get; set; }
        public string Address { get; set; }
        public string ContactPhone { get; set; }

        public virtual Partner Partner { get; set; }
    }
}