// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestEkz.Entities
{
    public partial class Supplier
    {
        public Supplier()
        {
            Materials = new HashSet<Material>();
        }

        public int SupplierId { get; set; }
        public string SupplierType { get; set; }
        public string CompanyName { get; set; }
        public string TaxId { get; set; }
        public string LegalAddress { get; set; }
        public string ContactDetails { get; set; }
        public decimal? Rating { get; set; }

        public virtual ICollection<Material> Materials { get; set; }
    }
}